services:
  - name: docker:20.10.12-dind
    command: ["--mtu=1440"]
    alias: docker

stages:
  - build
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/web:latest
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_SSL_NO_VERIFY: "1"
  HTTPS_PROXY: "http://10.230.143.15:3128"
  HTTP_PROXY: "http://10.230.143.15:3128"
  NO_PROXY: "docker"

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTPS_PROXY .
    - docker push "$CI_REGISTRY_IMAGE"

deploy:
  stage: deploy
  before_script:
    - apk update && apk add --no-cache openssh openssh-client bash curl
  script:
    # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - chmod 400 $DEPLOY_KEY
    - ssh -o StrictHostKeyChecking=no -i $DEPLOY_KEY $SERVER_USER@$SERVER_IP "docker pull $CI_REGISTRY_IMAGE:latest"
    - ssh -o StrictHostKeyChecking=no -i $DEPLOY_KEY $SERVER_USER@$SERVER_IP "docker stop frontend || true && docker rm frontend || true"
    - ssh -o StrictHostKeyChecking=no -i $DEPLOY_KEY $SERVER_USER@$SERVER_IP "docker run -p 3000:80 -d --name frontend $CI_REGISTRY_IMAGE:latest"
