stages:
  - build

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/web:latest
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_SSL_NO_VERIFY: "1"
  HTTPS_PROXY: "http://10.230.143.15:3128"
  HTTP_PROXY: "http://10.230.143.15:3128"
  NO_PROXY: "docker"

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:20.10.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTPS_PROXY.
    - docker push "$CI_REGISTRY_IMAGE"
