export const GET_EMPLOYEES = 'STAFF/GET_EMPLOYEES';
export const SET_EMPLOYEE = 'STAFF/SET_EMPLOYEE';
export const NOT_FOUND_EMPLOYEE = 'STAFF/NOT_FOUND_EMPLOYEE';
export const GET_DEPARTMENTS = 'STAFF/GET_DEPARTMENTS';
export const SET_EMPLOYEES_QUERY_PARAMS = 'STAFF/SET_EMPLOYEES_QUERY_PARAMS';
export const SET_EMPLOYEES_PAGINATION = 'STAFF/SET_EMPLOYEES_PAGINATION';
export const RESET_EMPLOYEES_PAGINATION = 'STAFF/RESET_EMPLOYEES_PAGINATION';

export const SHOW_PRELOADER = 'PRELOADER/SHOW_PRELOADER';
export const HIDE_PRELOADER = 'PRELOADER/HIDE_PRELOADER';

export const SHOW_FAIL_API_MODAL = 'MODAL/SHOW_FAIL_API_MODAL';

export const SET_MAIN_SCHEDULE_INPUT = 'SHEET/SET_MAIN_SCHEDULE_INPUT';
export const SET_MAIN_SCHEDULE_OUTPUT = 'SHEET/SET_MAIN_SCHEDULE_OUTPUT';
export const RESET_MAIN_SCHEDULE_OUTPUT = 'SHEET/RESET_MAIN_SCHEDULE_OUTPUT';
export const SET_MAIN_SCHEDULE_PAGINATION = 'SHEET/SET_MAIN_SCHEDULE_PAGINATION';
export const SET_SCHEDULE_QUERY_PARAMS = 'SHEET/SET_SCHEDULE_QUERY_PARAMS';

export const SET_STAFF_RATE_DATA = 'STAFF_RATE/SET_DATA';
export const SET_STAFF_RATE_DATA_OUTPUT = 'STAFF_RATE/SET_DATA_OUTPUT';
