export const GET_EMPLOYEES = 'STAFF/GET_EMPLOYEES';

export const SHOW_PRELOADER = 'PRELOADER/SHOW_PRELOADER';
export const HIDE_PRELOADER = 'PRELOADER/HIDE_PRELOADER';

export const SHOW_FAIL_API_MODAL = 'MODAL/SHOW_FAIL_API_MODAL';

export const SET_MAIN_SCHEDULE_INPUT = 'SHEET/SET_MAIN_SCHEDULE_INPUT';
export const SET_MAIN_SCHEDULE_OUTPUT = 'SHEET/SET_MAIN_SCHEDULE_OUTPUT';
export const SET_MAIN_SCHEDULE_PAGINATION = 'SHEET/SET_MAIN_SCHEDULE_PAGINATION';